<?php
/**
 * Custom Fields
 *
 * @since   1.0.0
 * @package Site_Functionality
 */

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if( function_exists( 'acf_add_local_field_group' ) ) {

	acf_add_local_field_group( array(
		'key' => 'group_event_details',
		'title' => __( 'Event Details', 'site-functionality' ),
		'fields' => array(
			array(
				'key' => 'field_event_cta',
				'label' => __( 'Call to Action', 'site-functionality' ),
				'name' => 'cta',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_event_recurrence_description',
				'label' => __( 'Recurrence Description', 'site-functionality' ),
				'name' => 'recurrence_description',
				'type' => 'textarea',
				'instructions' => __( 'Enter textual representation of recurring dates (e.g. Every third Wednesday of the Month)', 'site-functionality' ),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	/**
	 * Intro Section
	 */
	acf_add_local_field_group(array(
		'key' => 'group_alternate_intro',
		'title' => __( 'Intro Section', 'site-function' ),
		'fields' => array(
			array(
				'key' => 'field_5dc76f92f5d62',
				'label' => __( 'Headline', 'site-function' ),
				'name' => 'intro-title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc76fa0f5d63',
				'label' => __( 'Content', 'site-function' ),
				'name' => 'intro-content',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_5dc76fb5f5d64',
				'label' => __( 'Link', 'site-function' ),
				'name' => 'intro-link',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_5dc7760015098',
				'label' => __( 'File Link', 'site-function' ),
				'name' => 'intro-file',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'pdf',
			),
			array(
				'key' => 'field_intro-file-text',
				'label' => __( 'File Link Text', 'site-function' ),
				'name' => 'intro-file-text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '=',
					'value' => 'page-templates/locations.php',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'discussion',
			1 => 'comments',
			2 => 'revisions',
			3 => 'author',
			4 => 'format',
			5 => 'categories',
			6 => 'tags',
			7 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5dc76f87c06f9',
		'title' => __( 'Intro Section', 'site-function' ),
		'fields' => array(
			array(
				'key' => 'field_5dc76f92f5d62',
				'label' => __( 'Headline', 'site-function' ),
				'name' => 'intro-title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dc76fa0f5d63',
				'label' => __( 'Content', 'site-function' ),
				'name' => 'intro-content',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'basic',
				'media_upload' => 0,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '!=',
					'value' => 'page-templates/front-page.php',
				),
				array(
					'param' => 'page_template',
					'operator' => '!=',
					'value' => 'page-templates/news-events.php',
				),
				array(
					'param' => 'page_template',
					'operator' => '!=',
					'value' => 'page-templates/locations.php',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'discussion',
			1 => 'comments',
			2 => 'revisions',
			3 => 'author',
			4 => 'format',
			5 => 'categories',
			6 => 'tags',
			7 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
	));

	/**
	 * Featured Event
	 */
	acf_add_local_field_group(array(
		'key' => 'group_5dc77eb8e5e4a',
		'title' => __( 'Featured Event', 'site-functions' ),
		'fields' => array(
			array(
				'key' => 'field_5dc77eb91ff0a',
				'label' => __( 'Type', 'site-functions' ),
				'name' => 'type',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'dynamic' => 'Dynamic',
					'manual' => 'Manual',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'dynamic',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5dc77eb91ff67',
				'label' => __( 'Manual Post', 'site-functions' ),
				'name' => 'manual_post',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5dc77eb91ff0a',
							'operator' => '==',
							'value' => 'manual',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5dc77eb92f969',
						'label' => __( 'Title', 'site-functions' ),
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5dc77eb92f9e1',
						'label' => __( 'Excerpt', 'site-functions' ),
						'name' => 'content',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_5dc77eb92fa49',
						'label' => __( 'Image', 'site-functions' ),
						'name' => 'image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5dc77eb92faac',
						'label' => __( 'Link', 'site-functions' ),
						'name' => 'link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
				),
			),
			array(
				'key' => 'field_5dc77eb93d4b3',
				'label' => __( 'Event', 'site-functions' ),
				'name' => 'post',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5dc77eb91ff0a',
							'operator' => '!=',
							'value' => 'manual',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'event',
				),
				'taxonomy' => '',
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-templates/news-events.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
		),
		'active' => true,
		'description' => '',
	));

	/**
	 * Home Page Fields
	 */
	acf_add_local_field_group(array(
		'key' => 'group_5dc7684d79aaa',
		'title' => 'Home Sections',
		'fields' => array(
			array(
				'key' => 'field_5dc768709951e',
				'label' => 'Hero',
				'name' => 'hero',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5dc768869951f',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5dc7689299520',
						'label' => 'Headline',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5dc768a499521',
						'label' => 'Content',
						'name' => 'content',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => '',
					),
					array(
						'key' => 'field_5dc768be99522',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
				),
			),
			array(
				'key' => 'field_5dc768ed50b23',
				'label' => 'Number Counter',
				'name' => 'number_counter',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5dc76a1609548',
				'min' => 1,
				'max' => 4,
				'layout' => 'row',
				'button_label' => 'Add Number',
				'sub_fields' => array(
					array(
						'key' => 'field_5dc76a1609548',
						'label' => 'Number',
						'name' => 'number',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'table',
						'sub_fields' => array(
							array(
								'key' => 'field_5dc76a550954c',
								'label' => 'Number',
								'name' => 'number',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_5dc76a3b0954b',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							// array(
							// 	'key' => 'field_5dc76a2609549',
							// 	'label' => 'Title',
							// 	'name' => 'title',
							// 	'type' => 'text',
							// 	'instructions' => '',
							// 	'required' => 0,
							// 	'conditional_logic' => 0,
							// 	'wrapper' => array(
							// 		'width' => '',
							// 		'class' => '',
							// 		'id' => '',
							// 	),
							// 	'default_value' => '',
							// 	'placeholder' => '',
							// 	'prepend' => '',
							// 	'append' => '',
							// 	'maxlength' => '',
							// ),
							array(
								'key' => 'field_5dc76a2c0954a',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'textarea',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => 3,
								'new_lines' => '',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5dc769d609546',
				'label' => 'Posts',
				'name' => 'posts',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5dc76c3e767f1',
						'label' => 'Section Title',
						'name' => 'section_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5dc769f209547',
						'label' => 'Posts',
						'name' => 'posts',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => 'field_5dc76d30594fc',
						'min' => 0,
						'max' => 0,
						'layout' => 'row',
						'button_label' => 'Add Post',
						'sub_fields' => array(
							array(
								'key' => 'field_5dc76d30594fc',
								'label' => 'Type',
								'name' => 'type',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'dynamic' => 'Dynamic',
									'manual' => 'Manual',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'dynamic',
								'layout' => 'horizontal',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_5dc76cb882b77',
								'label' => 'Manual Post',
								'name' => 'manual_post',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5dc76d30594fc',
											'operator' => '==',
											'value' => 'manual',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'row',
								'sub_fields' => array(
									array(
										'key' => 'field_5dc76cc782b78',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5dc76ccd82b79',
										'label' => 'Excerpt',
										'name' => 'content',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
									array(
										'key' => 'field_5dc76ce882b7a',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'medium',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5dc76cf482b7b',
										'label' => 'Link',
										'name' => 'link',
										'type' => 'link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
									),
								),
							),
							array(
								'key' => 'field_5dc76d7b594fd',
								'label' => 'Post',
								'name' => 'post',
								'type' => 'post_object',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5dc76d30594fc',
											'operator' => '==',
											'value' => 'dynamic',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'post_type' => array(
									0 => 'page',
									1 => 'event',
									2 => 'post',
								),
								'taxonomy' => '',
								'allow_null' => 0,
								'multiple' => 0,
								'return_format' => 'object',
								'ui' => 1,
							),
						),
					),
				),
			),
			array(
				'key' => 'field_5dc76dd7c85f3',
				'label' => __( 'Callout', 'site-functions' ),
				'name' => 'blurb',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5dc76de9c85f4',
						'label' => 'Title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5dc76df1c85f5',
						'label' => 'Content',
						'name' => 'content',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_5dc76e03c85f6',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
				),
			),
			array(
				'key' => 'field_5dc76e2dcf545',
				'label' => 'Twitter Feed',
				'name' => 'twitter_handle',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'CTLegal',
				'prepend' => '@',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-templates/front-page.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	/**
	 * Landing Page Fields for Sections Block
	 */
	acf_add_local_field_group( array(
		'key' => 'group_5dc70d75489e8',
		'title' => __( 'Main Page Sections', 'site-functions' ),
		'fields' => array(
			array(
				'key' => 'field_5dc70d98a3cbe',
				'label' => __( 'Sections', 'site-functions' ),
				'name' => 'sections',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_5dc70dbfa3cbf',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => __( 'Add Section', 'site-functions' ),
				'sub_fields' => array(
					array(
						'key' => 'field_5dc70dbfa3cbf',
						'label' => __( 'Title', 'site-functions' ),
						'name' => 'title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5dc70dc6a3cc0',
						'label' => __( 'Content', 'site-functions' ),
						'name' => 'content',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_5dc70dcda3cc1',
						'label' => __( 'Image', 'site-functions' ),
						'name' => 'image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'medium',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
					array(
						'key' => 'field_5dc70dd3a3cc2',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-templates/grid-content.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	

	/**
	 * Landing Page Fields for Sections Block
	 */
	// acf_add_local_field_group(array(
	// 	'key' => 'group_5dc70d75489e8',
	// 	'title' => __( 'Sections', 'site-functions' ),
	// 	'fields' => array(
	// 		array(
	// 			'key' => 'field_5dc70d98a3cbe',
	// 			'label' => __( 'Sections', 'site-functions' ),
	// 			'name' => 'sections',
	// 			'type' => 'repeater',
	// 			'instructions' => '',
	// 			'required' => 0,
	// 			'conditional_logic' => 0,
	// 			'wrapper' => array(
	// 				'width' => '',
	// 				'class' => '',
	// 				'id' => '',
	// 			),
	// 			'collapsed' => 'field_5dc70dbfa3cbf',
	// 			'min' => 0,
	// 			'max' => 0,
	// 			'layout' => 'row',
	// 			'button_label' => __( 'Add Section', 'site-functions' ),
	// 			'sub_fields' => array(
	// 				array(
	// 					'key' => 'field_5dc70dbfa3cbf',
	// 					'label' => __( 'Title', 'site-functions' ),
	// 					'name' => 'title',
	// 					'type' => 'text',
	// 					'instructions' => '',
	// 					'required' => 0,
	// 					'conditional_logic' => 0,
	// 					'wrapper' => array(
	// 						'width' => '',
	// 						'class' => '',
	// 						'id' => '',
	// 					),
	// 					'default_value' => '',
	// 					'placeholder' => '',
	// 					'prepend' => '',
	// 					'append' => '',
	// 					'maxlength' => '',
	// 				),
	// 				array(
	// 					'key' => 'field_5dc70dc6a3cc0',
	// 					'label' => __( 'Content', 'site-functions' ),
	// 					'name' => 'content',
	// 					'type' => 'wysiwyg',
	// 					'instructions' => '',
	// 					'required' => 0,
	// 					'conditional_logic' => 0,
	// 					'wrapper' => array(
	// 						'width' => '',
	// 						'class' => '',
	// 						'id' => '',
	// 					),
	// 					'default_value' => '',
	// 					'tabs' => 'all',
	// 					'toolbar' => 'basic',
	// 					'media_upload' => 0,
	// 					'delay' => 0,
	// 				),
	// 				array(
	// 					'key' => 'field_5dc70dcda3cc1',
	// 					'label' => __( 'Image', 'site-functions' ),
	// 					'name' => 'image',
	// 					'type' => 'image',
	// 					'instructions' => '',
	// 					'required' => 0,
	// 					'conditional_logic' => 0,
	// 					'wrapper' => array(
	// 						'width' => '',
	// 						'class' => '',
	// 						'id' => '',
	// 					),
	// 					'return_format' => 'array',
	// 					'preview_size' => 'medium',
	// 					'library' => 'all',
	// 					'min_width' => '',
	// 					'min_height' => '',
	// 					'min_size' => '',
	// 					'max_width' => '',
	// 					'max_height' => '',
	// 					'max_size' => '',
	// 					'mime_types' => '',
	// 				),
	// 				array(
	// 					'key' => 'field_5dc70dd3a3cc2',
	// 					'label' => 'Link',
	// 					'name' => 'link',
	// 					'type' => 'link',
	// 					'instructions' => '',
	// 					'required' => 0,
	// 					'conditional_logic' => 0,
	// 					'wrapper' => array(
	// 						'width' => '',
	// 						'class' => '',
	// 						'id' => '',
	// 					),
	// 					'return_format' => 'array',
	// 				),
	// 			),
	// 		),
	// 	),
	// 	'location' => array(
	// 		array(
	// 			array(
	// 				'param' => 'block',
	// 				'operator' => '==',
	// 				'value' => 'acf/subsections',
	// 			),
	// 		),
	// 	),
	// 	'menu_order' => 0,
	// 	'position' => 'normal',
	// 	'style' => 'default',
	// 	'label_placement' => 'top',
	// 	'instruction_placement' => 'label',
	// 	'hide_on_screen' => '',
	// 	'active' => true,
	// 	'description' => '',
	// ));

	
}